version: '3.7'

services:

  redis:
    image: redis:alpine
    networks:
      - webnet
    ports:
      - 6379:6379
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

networks:
  webnet:
